# default parameters
seed = 12
name = 'fixed_key_phrase_chunk_rep_bs_bert_2024'
retain_ckp = true
# 5 0.1_0.6 0,5305
# key_phrase_chunk_rep fixed_weights 50 0.1_0.7 0.5332
# key_phrase_chunk_rep fixed_weights 50 0.1_0.8 0.5334
[PARAMSGRID]
MODEL_-attn_mode=[

# {name='key_phrase_chunk_rep',param1=50,param2='ori_scores_1'},
# {name='key_phrase_chunk_rep',param1=10,param2='ori_scores_1'},
# {name='key_phrase_chunk_rep',param1=5,param2='ori_scores_1'},
# {name='key_phrase_chunk_rep',param1=3,param2='ori_scores_1'},
# {name='key_phrase_chunk_rep2',param1=50,param2='fixed_weights',param3='0.1_0.9'},
# {name='key_phrase_chunk_rep2',param1=10,param2='fixed_weights',param3='0.1_0.9'},
# {name='key_phrase_chunk_rep2',param1=5,param2='fixed_weights',param3='0.1_0.9'},
# {name='key_phrase_chunk_rep2',param1=3,param2='fixed_weights',param3='0.1_0.9'},
{name='key_phrase_chunk_rep',param1=50,param2='average_weights',param3='0.1_0.5'},
{name='key_phrase_chunk_rep',param1=10,param2='average_weights',param3='0.1_0.5'},
{name='key_phrase_chunk_rep',param1=5,param2='average_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep',param1=50,param2='ori_scores_1'},
# {name='key_phrase_chunk_rep',param1=10,param2='ori_scores_1'},
# {name='key_phrase_chunk_rep',param1=5,param2='ori_scores_1'},
# {name='key_phrase_chunk_rep',param1=3,param2='ori_scores_1'},

]
[EXPERIMENT]
devices = 1
accelerator = 'gpu'
epochs = 50
accumulate_grad_batches = 1
save_path = 'results/experiments/fixed_key_phrase_chunk_rep_bs_bert_2024/'
val_check_interval = 1.0
precision = 32
# optimizer = 'adam'
# optimizer_params = {}
# lrscheduler = 'linearwarmup'
optimizer = 'adamw'
optimizer_params = {}
lrscheduler = 'cosinewarmup'
lrscheduler_params={}
lr = 0.00005
monitor = 'val_micro_f1'
mode = 'max'
loss = 'bce' # ce_1, ce
warmup = 0.1
# steps = 3000
stop_strategy = 'early_stop'
stop_patience = 10
  
[MODEL]
name = 'BERT'
model_name = 'bert-base-uncased'
num_labels = 227
freeze = false
embedding  = {initialization='chunk_pretrain_emb', kwargs={model_name='bert-base-uncased', dim=768,freeze=false,way='sum',norm=true}}
# attn_mode = {name='key_phrase_chunk_rep',param1=5,param2='fixed_weights',param3='0.1_0.8'}
attn_mode = {name='key_phrase_chunk_rep',param1=5,param2='ori_scores_1'}
pvalue = 0.5

[DATA]
datasets_dir = 'data'
dataset_name = 'bs'
batch_size = 16
train_ratio = 1
val_split_ratio = 0.1
num_workers = 0
max_seq_len = 510
tokenizer_type = "bert"
# tokenizer_name = 'wordpiece'
tokenizer_name = 'bert-base-uncased'
tokenizer_params = {clean=true,lowercase=true,add_spe_tokens=['[LOC]']}
processer = {name='bs'}







