# default parameters
seed = 0
name = 'fixed_key_phrase_chunk_rep_eurlex_inverse_bert'
retain_ckp = false
[EXPERIMENT]
devices = 1
accelerator = 'gpu'
epochs = 100
accumulate_grad_batches = 1
save_path = 'results/experiments/fixed_key_phrase_chunk_rep_eurlex_inverse_bert/'
val_check_interval = 1.0
precision = 32
# optimizer = 'adamw'
# optimizer_params = {}
# lrscheduler = 'cosinewarmup'
# lrscheduler_params={}
optimizer = 'adam'
optimizer_params = {}
lrscheduler = 'linearwarmup'
lrscheduler_params={}
lr = 0.00005
monitor = 'val_micro_f1'
mode = 'max'
loss = 'bce' # ce_1, ce
warmup = 0.05
# steps = 3000
stop_strategy = 'early_stop'
stop_patience = 10
  
[MODEL]
name = 'BERT'
model_name = 'bert-base-uncased'
num_labels = 4271
freeze = false
embedding  = {initialization='chunk_pretrain_emb', kwargs={model_name='bert-base-uncased', dim=768,freeze=false,way='sum',norm=true}}
attn_mode = {name='key_phrase_chunk_rep',param1=50,param2='fixed_weights',param3='0.1_0.8'}

[DATA]
datasets_dir = 'data'
dataset_name = 'eurlex-inverse'
batch_size = 16
train_ratio = 1
num_workers = 0
max_seq_len = 510
tokenizer_type = "bert"
tokenizer_name = 'bert-base-uncased'
tokenizer_params = {clean=true,lowercase=true,add_spe_tokens=['[LOC]']}
processer = {name='eurlex'}







