# default parameters
seed = 10
name = 'bert_lun'
retain_ckp = true
[EXPERIMENT]
devices = 1
accelerator = 'gpu'
epochs = 10
accumulate_grad_batches = 1
save_path = 'results/experiments/bert_lun/'
val_check_interval = 1.0
precision = 32
optimizer = 'adamw'
optimizer_params = {}
lrscheduler = 'cosinewarmup'
lrscheduler_params={}
lr = 0.00005
monitor = 'val_loss'
mode = 'min'
loss = 'ce' # ce_1, ce
warmup = 0.1
# steps = 3000
stop_strategy = 'early_stop'
  
[MODEL]
name = 'BERT'
model_name = 'allenai/longformer-base-4096'
num_labels = 3
freeze = false
embedding  = {initialization='original'}
attn_mode = {name='default',param1=0}
# attn_mode = {name='key_phrase_split',param1=10,param2='all_locs'}

[DATA]
datasets_dir = 'data'
dataset_name = 'lun'
batch_size=8
train_ratio= 1
val_split_ratio = 0.1
num_workers = 0
max_seq_len = 4096
tokenizer_type = "bert"
tokenizer_name =  'allenai/longformer-base-4096'
tokenizer_params = {clean=true,lowercase=true,add_spe_tokens=['[LOC]']}
processer = {name='LongformerHp'}







