# default parameters
seed = 10
name = 'key_phrase_chunk_rep_lun_bert'
retain_ckp = true
[PARAMSGRID]
MODEL_-attn_mode=[
# {name='key_phrase_chunk_rep',param1=500,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep',param1=200,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep',param1=50,param2='fixed_weights',param3='0.1_0.5'},
{name='key_phrase_chunk_rep',param1=10,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep',param1=5,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep',param1=3,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep2',param1=50,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep2',param1=10,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep2',param1=5,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep',param1=50,param2='average_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep',param1=10,param2='average_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep',param1=5,param2='average_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep2',param1=500,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep2',param1=200,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep2',param1=50,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep2',param1=10,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep2',param1=5,param2='fixed_weights',param3='0.1_0.5'},
# {name='key_phrase_chunk_rep2',param1=1,param2='fixed_weights',param3='0.1_0.5'},
]
[EXPERIMENT]
devices = 1
accelerator = 'gpu'
epochs = 100
accumulate_grad_batches = 1
save_path = 'results/experiments/key_phrase_chunk_rep_lun_bert/'
val_check_interval = 1.0
precision = 32
# optimizer = 'adamw'
# optimizer_params = {}
# lrscheduler = 'cosinewarmup'
# lrscheduler_params={}
optimizer = 'adam'
optimizer_params = {}
lrscheduler = 'linearwarmup'
lrscheduler_params={}
lr = 0.00005
monitor = 'val_acc'
mode = 'max'
loss = 'ce' # ce_1, ce
warmup = 0.1
# steps = 3000
stop_strategy = 'early_stop'
  
[MODEL]
name = 'BERT'
model_name = 'bert-base-uncased'
num_labels = 3
freeze = false
embedding  = {initialization='chunk_pretrain_emb', kwargs={model_name='bert-base-uncased', dim=768,freeze=false,way='sum',norm=true}}
attn_mode = {name='key_phrase_chunk_rep',param1=10,param2='fixed_weights',param3='0.1_0.5'}

[DATA]
datasets_dir = 'data'
dataset_name = 'lun'
batch_size=32
train_ratio= 1
val_split_ratio = 0.1
num_workers = 0
max_seq_len = 510
tokenizer_type = "bert"
tokenizer_name =  'bert-base-uncased'
tokenizer_params = {clean=true,lowercase=true,add_spe_tokens=['[LOC]']}
processer = {name='LongformerHp'}







